services:
  neo4j:
    image: neo4j:5.26
    ports: ["7474:7474", "7687:7687"] #maps port from mac to container
    environment:
      NEO4J_AUTH: neo4j/devpassword
    volumes: [neo4jdata:/data]
volumes: { neo4jdata: }